name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: llvm/actions/install-ninja@main
      - name: Configure llvm cmake
        run:  cmake -Bbuild -Sllvm -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="lld;clang"
      - name: Build clang
        run:  cmake --build build --target clang
      - name: Build llvm-rc
        run:  cmake --build build --target llvm-rc
      - name: Build lld
        run:  cmake --build build --target lld
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: llvm-${{ matrix.os }}
          path: build/**/bin
